import type { AmbientConfig, AmbientState } from "@/types/ambient";

/**
 * Configuração completa dos Estados Ambientais.
 * Cada estado define: keywords (primary/secondary/exclude), tema visual, layout sugerido e CTA.
 */
export const AMBIENT_STATES: Record<AmbientState, AmbientConfig> = {
  neutral: {
    state: "neutral",
    label: "Neutro",
    emoji: "✏️",
    keywords: {
      primary: [],
      secondary: [],
      exclude: [],
    },
    theme: {
      bg: "#1a1a2e",
      text: "#eaeaea",
      accent: "#6366f1",
      className: "",
    },
    layout: "centered",
    ctaText: "Criar Post",
  },

  motivational: {
    state: "motivational",
    label: "Motivação",
    emoji: "✨",
    keywords: {
      primary: [
        "nunca desista",
        "você consegue",
        "acredite",
        "superação",
        "transformação",
        "inspire",
        "motivação",
        "conquista",
      ],
      secondary: [
        "sonho",
        "objetivo",
        "meta",
        "foco",
        "coragem",
        "persistência",
        "força",
        "vitória",
        "vencer",
        "campeão",
        "guerreiro",
        "determinação",
        "confiança",
        "bora",
        "vai dar certo",
        "glória",
      ],
      exclude: ["promoção", "desconto", "compre", "r$", "oferta", "grátis"],
    },
    theme: {
      bg: "#0f0f1a",
      text: "#fef08a",
      accent: "#facc15",
      className: "",
    },
    layout: "centered",
    ctaText: "Inspirar Agora ✨",
  },

  informative: {
    state: "informative",
    label: "Informativo",
    emoji: "💡",
    keywords: {
      primary: [
        "você sabia",
        "curiosidade",
        "fato",
        "estudo mostra",
        "pesquisa",
        "saiba",
        "notícia",
      ],
      secondary: [
        "dica",
        "estudo",
        "news",
        "dados",
        "estatística",
        "informação",
        "importante",
        "atenção",
        "novidade",
        "atualização",
        "trend",
        "tendência",
        "relatório",
        "análise",
        "descoberta",
        "insight",
      ],
      exclude: ["revelado", "escândalo", "mentira", "fraude"],
    },
    theme: {
      bg: "#0a1929",
      text: "#e0f2fe",
      accent: "#38bdf8",
      className: "",
    },
    layout: "card",
    ctaText: "Compartilhar Insight 💡",
  },

  promotional: {
    state: "promotional",
    label: "Promoção",
    emoji: "🔥",
    keywords: {
      primary: [
        "desconto",
        "promoção",
        "oferta",
        "% off",
        "de r$",
        "por apenas",
        "50%",
        "30%",
        "70%",
        "black friday",
      ],
      secondary: [
        "aproveite",
        "exclusivo",
        "grátis",
        "free",
        "bônus",
        "condição especial",
        "preço",
        "economia",
        "somente hoje",
        "últimas unidades",
        "queima",
        "sale",
        "compre",
        "venda",
      ],
      exclude: [],
    },
    theme: {
      bg: "#1c0a0a",
      text: "#fef2f2",
      accent: "#ef4444",
      className: "",
    },
    layout: "hierarchy",
    ctaText: "Criar Oferta 🔥",
  },

  personal: {
    state: "personal",
    label: "Pessoal",
    emoji: "💭",
    keywords: {
      primary: [
        "minha história",
        "minha jornada",
        "eu aprendi",
        "desabafo",
        "minha vida",
        "confissão",
      ],
      secondary: [
        "eu",
        "senti",
        "jornada",
        "aprendi",
        "reflexão",
        "pessoal",
        "íntimo",
        "experiência",
        "me sinto",
        "meu caminho",
        "quando eu",
        "lembro",
        "recordo",
        "memória",
        "nostalgia",
        "sentimento",
        "emoção",
        "vulnerável",
        "abrir o coração",
        "sincero",
      ],
      exclude: ["promoção", "oferta", "desconto", "compre"],
    },
    theme: {
      bg: "#fef3e2",
      text: "#422006",
      accent: "#d97706",
      className: "",
    },
    layout: "split",
    ctaText: "Contar História 💭",
  },

  educational: {
    state: "educational",
    label: "Educacional",
    emoji: "📚",
    keywords: {
      primary: [
        "como fazer",
        "passo a passo",
        "tutorial",
        "aprenda",
        "guia",
        "como ser",
        "como conseguir",
      ],
      secondary: [
        "dicas para",
        "técnica",
        "método",
        "ensino",
        "aula",
        "curso",
        "treinamento",
        "estratégia",
        "segredo",
        "hack",
        "macete",
        "primeiro passo",
        "segundo",
        "terceiro",
        "etapa",
        "fase",
        "processo",
        "framework",
        "modelo",
        "template",
        "checklist",
        "produtivo",
        "produtividade",
      ],
      exclude: ["desconto", "oferta", "promoção", "r$"],
    },
    theme: {
      bg: "#052e16",
      text: "#dcfce7",
      accent: "#22c55e",
      className: "",
    },
    layout: "carousel",
    ctaText: "Criar Tutorial 📚",
  },

  controversial: {
    state: "controversial",
    label: "Polêmico",
    emoji: "⚡",
    keywords: {
      primary: [
        "pare de",
        "não faça",
        "mentira",
        "revelado",
        "escândalo",
        "verdade nua",
        "por que ninguém",
      ],
      secondary: [
        "erro",
        "pare",
        "verdade",
        "cuidado",
        "absurdo",
        "chocante",
        "urgente",
        "alerta",
        "perigo",
        "evite",
        "polêmico",
        "controverso",
        "tabu",
        "proibido",
        "segredo sujo",
        "exposto",
        "fraude",
        "golpe",
        "fake",
        "mito",
        "o que não",
      ],
      exclude: ["tutorial", "aprenda", "passo a passo"],
    },
    theme: {
      bg: "#0a0a0a",
      text: "#fef08a",
      accent: "#eab308",
      className: "",
    },
    layout: "headline",
    ctaText: "Revelar Verdade ⚡",
  },
};

/** Retorna a configuração de um estado */
export function getAmbientConfig(state: AmbientState): AmbientConfig {
  return AMBIENT_STATES[state];
}

/** Retorna todos os estados disponíveis */
export function getAllStates(): AmbientState[] {
  return Object.keys(AMBIENT_STATES) as AmbientState[];
}

/** Retorna o config padrão (neutral) */
export function getDefaultConfig(): AmbientConfig {
  return AMBIENT_STATES.neutral;
}
