import type { PostVariation } from '@shared/postspark';
import { createPostVisualSnapshot } from '@/lib/variationSnapshot';

export interface Landing2Demo {
  id: string;
  chip: string;
  title: string;
  prompt: string;
  outcome: string;
  variations: PostVariation[];
}

const baseVariation = {
  hashtags: [] as string[],
  tone: 'professional',
  platform: 'instagram',
  aspectRatio: '1:1',
  postMode: 'static',
} satisfies Partial<PostVariation>;

export const LANDING2_DEMOS: Landing2Demo[] = [
  {
    id: 'restaurant-promo',
    chip: 'Promoção',
    title: 'Restaurante divulgando oferta',
    prompt: 'preciso divulgar o combo de almoço da semana, sem parecer panfleto barato',
    outcome: 'Oferta mais clara, visual premium e CTA pronto para publicar.',
    variations: [
      {
        ...baseVariation,
        id: 'restaurant-promo-1',
        headline: 'Almoço da semana com cara de escolha certa.',
        body: 'Combo completo, visual limpo e uma chamada que vende sem gritar.',
        caption: 'Almoço da semana com cara de escolha certa.\n\nCombo completo, visual limpo e uma chamada que vende sem gritar.',
        callToAction: 'Reservar meu combo',
        imagePrompt: 'premium lunch plate, modern restaurant table, warm natural light, appetizing food photography',
        imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#120D0A',
        textColor: '#FFF5EA',
        headlineColor: '#FFF5EA',
        bodyColor: '#E8CDB6',
        accentColor: '#FF7A2F',
        layout: 'split',
        designTokens: {
          colors: { background: '#120D0A', primary: '#FF7A2F', secondary: '#FFF5EA', text: '#FFF5EA', card: '#221610' },
          typography: { fontFamily: '"Arial Black", "Arial", sans-serif', customFontUrl: '', originalFont: 'Arial Black', textTransform: 'uppercase', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: '0 20px 40px rgba(0,0,0,0.45)', border: 'none' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'restaurant-promo-2',
        headline: 'Seu horário de almoço merece uma pausa melhor.',
        body: 'Uma peça mais acolhedora para atrair quem decide rápido perto do meio-dia.',
        caption: 'Seu horário de almoço merece uma pausa melhor.\n\nUma peça mais acolhedora para atrair quem decide rápido perto do meio-dia.',
        callToAction: 'Ver cardápio',
        imagePrompt: 'cozy restaurant lunch, warm editorial food photography, elegant table setting',
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#1A1210',
        textColor: '#FFF7F0',
        headlineColor: '#FFF7F0',
        bodyColor: '#E6D2C4',
        accentColor: '#E9A24B',
        layout: 'minimal',
        designTokens: {
          colors: { background: '#1A1210', primary: '#E9A24B', secondary: '#FFF7F0', text: '#FFF7F0', card: '#281C18' },
          typography: { fontFamily: 'Georgia, "Times New Roman", serif', customFontUrl: '', originalFont: 'Georgia', textTransform: 'none', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: '1px solid rgba(233,162,75,0.18)' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'restaurant-promo-3',
        headline: 'Combo da semana. Preço direto. Vontade imediata.',
        body: 'Versão objetiva para story, feed e anúncio local.',
        caption: 'Combo da semana. Preço direto. Vontade imediata.\n\nVersão objetiva para story, feed e anúncio local.',
        callToAction: 'Pedir agora',
        imagePrompt: 'bold restaurant promotion, grilled food, dark background, orange accent, modern ad',
        imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#070707',
        textColor: '#FFFFFF',
        headlineColor: '#FFFFFF',
        bodyColor: '#D8D8D8',
        accentColor: '#FF5B1A',
        layout: 'centered',
        designTokens: {
          colors: { background: '#070707', primary: '#FF5B1A', secondary: '#FFFFFF', text: '#FFFFFF', card: '#171717' },
          typography: { fontFamily: '"Arial Black", "Arial", sans-serif', customFontUrl: '', originalFont: 'Arial Black', textTransform: 'uppercase', textAlign: 'center' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: 'none' },
          decorations: 'minimal',
        },
      },
    ],
  },
  {
    id: 'service-authority',
    chip: 'Serviço',
    title: 'Serviço local ganhando confiança',
    prompt: 'sou eletricista e quero postar que atendo emergência 24h sem parecer amador',
    outcome: 'Mensagem mais confiável, visual profissional e promessa fácil de entender.',
    variations: [
      {
        ...baseVariation,
        id: 'service-authority-1',
        headline: 'Problema elétrico não espera horário comercial.',
        body: 'Atendimento 24h com comunicação clara, confiança e presença profissional.',
        caption: 'Problema elétrico não espera horário comercial.\n\nAtendimento 24h com comunicação clara, confiança e presença profissional.',
        callToAction: 'Chamar no WhatsApp',
        imagePrompt: 'professional electrician at work, dark premium lighting, sparks, clean service brand photography',
        imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#061016',
        textColor: '#F4FBFF',
        headlineColor: '#F4FBFF',
        bodyColor: '#C6D7E2',
        accentColor: '#19D3E6',
        layout: 'split',
        designTokens: {
          colors: { background: '#061016', primary: '#19D3E6', secondary: '#F4FBFF', text: '#F4FBFF', card: '#0D1D26' },
          typography: { fontFamily: '"Arial Black", "Arial", sans-serif', customFontUrl: '', originalFont: 'Arial Black', textTransform: 'uppercase', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: '0 18px 38px rgba(0,0,0,0.5)', border: 'none' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'service-authority-2',
        headline: 'Emergência resolvida com técnica, não improviso.',
        body: 'Um post para transformar urgência em confiança antes do primeiro contato.',
        caption: 'Emergência resolvida com técnica, não improviso.\n\nUm post para transformar urgência em confiança antes do primeiro contato.',
        callToAction: 'Solicitar atendimento',
        imagePrompt: 'clean tools on dark workbench, premium service photography, cyan highlights',
        imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#080B10',
        textColor: '#F8FAFC',
        headlineColor: '#F8FAFC',
        bodyColor: '#C9D4DF',
        accentColor: '#FFC24A',
        layout: 'minimal',
        designTokens: {
          colors: { background: '#080B10', primary: '#FFC24A', secondary: '#F8FAFC', text: '#F8FAFC', card: '#131820' },
          typography: { fontFamily: '"Trebuchet MS", "Segoe UI", sans-serif', customFontUrl: '', originalFont: 'Trebuchet MS', textTransform: 'uppercase', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: '1px solid rgba(255,194,74,0.22)' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'service-authority-3',
        headline: 'Quando a luz cai, sua marca precisa aparecer.',
        body: 'Versão mais memorável para destacar disponibilidade e resposta rápida.',
        caption: 'Quando a luz cai, sua marca precisa aparecer.\n\nVersão mais memorável para destacar disponibilidade e resposta rápida.',
        callToAction: 'Salvar contato',
        imagePrompt: 'dramatic city lights, power outage mood, professional emergency service ad',
        imageUrl: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#05060A',
        textColor: '#FFFFFF',
        headlineColor: '#FFFFFF',
        bodyColor: '#D7DDE6',
        accentColor: '#5CE1E6',
        layout: 'centered',
        designTokens: {
          colors: { background: '#05060A', primary: '#5CE1E6', secondary: '#FFFFFF', text: '#FFFFFF', card: '#10131B' },
          typography: { fontFamily: '"Segoe UI", "Helvetica Neue", sans-serif', customFontUrl: '', originalFont: 'Segoe UI', textTransform: 'none', textAlign: 'center' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: 'none' },
          decorations: 'minimal',
        },
      },
    ],
  },
  {
    id: 'social-media-calendar',
    chip: 'Social media',
    title: 'Social media entregando volume',
    prompt: 'preciso criar 3 posts para clínica estética essa semana: promoção, prova social e agenda aberta',
    outcome: 'Três direções prontas para apresentar, editar e publicar sem recomeçar do zero.',
    variations: [
      {
        ...baseVariation,
        id: 'social-media-calendar-1',
        headline: 'Agenda aberta para quem quer se cuidar ainda esta semana.',
        body: 'Um post direto para transformar intenção em horário marcado.',
        caption: 'Agenda aberta para quem quer se cuidar ainda esta semana.\n\nUm post direto para transformar intenção em horário marcado.',
        callToAction: 'Agendar avaliação',
        imagePrompt: 'premium aesthetic clinic, clean skincare treatment room, soft light, elegant visual identity',
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#101016',
        textColor: '#FFF7FB',
        headlineColor: '#FFF7FB',
        bodyColor: '#E7D8E0',
        accentColor: '#F06BA8',
        layout: 'split',
        designTokens: {
          colors: { background: '#101016', primary: '#F06BA8', secondary: '#FFF7FB', text: '#FFF7FB', card: '#1E1820' },
          typography: { fontFamily: '"Arial Black", "Arial", sans-serif', customFontUrl: '', originalFont: 'Arial Black', textTransform: 'uppercase', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: '0 18px 40px rgba(0,0,0,0.42)', border: 'none' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'social-media-calendar-2',
        headline: 'Resultado bonito também precisa parecer confiável.',
        body: 'Prova social com estética limpa para vender segurança, não exagero.',
        caption: 'Resultado bonito também precisa parecer confiável.\n\nProva social com estética limpa para vender segurança, não exagero.',
        callToAction: 'Ver horários',
        imagePrompt: 'minimal skincare product and soft towel, premium clinic branding, clean editorial',
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#F3EEE9',
        textColor: '#171313',
        headlineColor: '#171313',
        bodyColor: '#4F4444',
        accentColor: '#B84D74',
        layout: 'minimal',
        designTokens: {
          colors: { background: '#F3EEE9', primary: '#B84D74', secondary: '#171313', text: '#171313', card: '#E5DAD4' },
          typography: { fontFamily: 'Georgia, "Times New Roman", serif', customFontUrl: '', originalFont: 'Georgia', textTransform: 'none', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: 'none' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'social-media-calendar-3',
        headline: 'Promoção com presença de marca, não cara de liquidação.',
        body: 'Uma chamada comercial mais refinada para campanha de clínica estética.',
        caption: 'Promoção com presença de marca, não cara de liquidação.\n\nUma chamada comercial mais refinada para campanha de clínica estética.',
        callToAction: 'Quero minha vaga',
        imagePrompt: 'elegant beauty clinic campaign, premium pink and black editorial composition',
        imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#0A0709',
        textColor: '#FFFFFF',
        headlineColor: '#FFFFFF',
        bodyColor: '#EADDE4',
        accentColor: '#FF4F93',
        layout: 'centered',
        designTokens: {
          colors: { background: '#0A0709', primary: '#FF4F93', secondary: '#FFFFFF', text: '#FFFFFF', card: '#181016' },
          typography: { fontFamily: '"Trebuchet MS", "Segoe UI", sans-serif', customFontUrl: '', originalFont: 'Trebuchet MS', textTransform: 'uppercase', textAlign: 'center' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: '1px solid rgba(255,79,147,0.22)' },
          decorations: 'minimal',
        },
      },
    ],
  },
];

export function createLanding2Snapshot(variation: PostVariation) {
  return createPostVisualSnapshot(variation, '1:1');
}
