import type { PostVariation } from '@shared/postspark';
import { createPostVisualSnapshot } from '@/lib/variationSnapshot';

export interface Landing2Demo {
  id: string;
  chip: string;
  title: string;
  prompt: string;
  outcome: string;
  variations: PostVariation[];
}

const baseVariation = {
  hashtags: [] as string[],
  tone: 'professional',
  platform: 'instagram',
  aspectRatio: '1:1',
  postMode: 'static',
} satisfies Partial<PostVariation>;

export const LANDING2_DEMOS: Landing2Demo[] = [
  {
    id: 'restaurant-promo',
    chip: 'Promoção',
    title: 'Restaurante divulgando oferta',
    prompt: 'preciso divulgar o combo de almoço da semana, sem parecer panfleto barato',
    outcome: 'Oferta mais clara, visual premium e CTA pronto para publicar.',
    variations: [
      {
        ...baseVariation,
        id: 'restaurant-promo-1',
        headline: 'Almoço da semana com cara de escolha certa.',
        body: 'Combo completo, visual limpo e uma chamada que vende sem gritar.',
        caption: 'Almoço da semana com cara de escolha certa.\n\nCombo completo, visual limpo e uma chamada que vende sem gritar.',
        callToAction: 'Reservar meu combo',
        imagePrompt: 'premium lunch plate, modern restaurant table, warm natural light, appetizing food photography',
        imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#120D0A',
        textColor: '#FFF5EA',
        headlineColor: '#FFF5EA',
        bodyColor: '#E8CDB6',
        accentColor: '#FF7A2F',
        layout: 'split',
        designTokens: {
          colors: { background: '#120D0A', primary: '#FF7A2F', secondary: '#FFF5EA', text: '#FFF5EA', card: '#221610' },
          typography: { fontFamily: '"Arial Black", "Arial", sans-serif', customFontUrl: '', originalFont: 'Arial Black', textTransform: 'uppercase', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: '0 20px 40px rgba(0,0,0,0.45)', border: 'none' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'restaurant-promo-2',
        headline: 'Seu horário de almoço merece uma pausa melhor.',
        body: 'Uma peça mais acolhedora para atrair quem decide rápido perto do meio-dia.',
        caption: 'Seu horário de almoço merece uma pausa melhor.\n\nUma peça mais acolhedora para atrair quem decide rápido perto do meio-dia.',
        callToAction: 'Ver cardápio',
        imagePrompt: 'cozy restaurant lunch, warm editorial food photography, elegant table setting',
        imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#1A1210',
        textColor: '#FFF7F0',
        headlineColor: '#FFF7F0',
        bodyColor: '#E6D2C4',
        accentColor: '#E9A24B',
        layout: 'minimal',
        designTokens: {
          colors: { background: '#1A1210', primary: '#E9A24B', secondary: '#FFF7F0', text: '#FFF7F0', card: '#281C18' },
          typography: { fontFamily: 'Georgia, "Times New Roman", serif', customFontUrl: '', originalFont: 'Georgia', textTransform: 'none', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: '1px solid rgba(233,162,75,0.18)' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'restaurant-promo-3',
        headline: 'Combo da semana. Preço direto. Vontade imediata.',
        body: 'Versão objetiva para story, feed e anúncio local.',
        caption: 'Combo da semana. Preço direto. Vontade imediata.\n\nVersão objetiva para story, feed e anúncio local.',
        callToAction: 'Pedir agora',
        imagePrompt: 'bold restaurant promotion, grilled food, dark background, orange accent, modern ad',
        imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#070707',
        textColor: '#FFFFFF',
        headlineColor: '#FFFFFF',
        bodyColor: '#D8D8D8',
        accentColor: '#FF5B1A',
        layout: 'centered',
        designTokens: {
          colors: { background: '#070707', primary: '#FF5B1A', secondary: '#FFFFFF', text: '#FFFFFF', card: '#171717' },
          typography: { fontFamily: '"Arial Black", "Arial", sans-serif', customFontUrl: '', originalFont: 'Arial Black', textTransform: 'uppercase', textAlign: 'center' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: 'none' },
          decorations: 'minimal',
        },
      },
    ],
  },
  {
    id: 'service-authority',
    chip: 'Serviço',
    title: 'Serviço local ganhando confiança',
    prompt: 'sou eletricista e quero postar que atendo emergência 24h sem parecer amador',
    outcome: 'Mensagem mais confiável, visual profissional e promessa fácil de entender.',
    variations: [
      {
        ...baseVariation,
        id: 'service-authority-1',
        headline: 'Problema elétrico não espera horário comercial.',
        body: 'Atendimento 24h com comunicação clara, confiança e presença profissional.',
        caption: 'Problema elétrico não espera horário comercial.\n\nAtendimento 24h com comunicação clara, confiança e presença profissional.',
        callToAction: 'Chamar no WhatsApp',
        imagePrompt: 'professional electrician at work, dark premium lighting, sparks, clean service brand photography',
        imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#061016',
        textColor: '#F4FBFF',
        headlineColor: '#F4FBFF',
        bodyColor: '#C6D7E2',
        accentColor: '#19D3E6',
        layout: 'split',
        designTokens: {
          colors: { background: '#061016', primary: '#19D3E6', secondary: '#F4FBFF', text: '#F4FBFF', card: '#0D1D26' },
          typography: { fontFamily: '"Arial Black", "Arial", sans-serif', customFontUrl: '', originalFont: 'Arial Black', textTransform: 'uppercase', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: '0 18px 38px rgba(0,0,0,0.5)', border: 'none' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'service-authority-2',
        headline: 'Emergência resolvida com técnica, não improviso.',
        body: 'Um post para transformar urgência em confiança antes do primeiro contato.',
        caption: 'Emergência resolvida com técnica, não improviso.\n\nUm post para transformar urgência em confiança antes do primeiro contato.',
        callToAction: 'Solicitar atendimento',
        imagePrompt: 'clean tools on dark workbench, premium service photography, cyan highlights',
        imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#080B10',
        textColor: '#F8FAFC',
        headlineColor: '#F8FAFC',
        bodyColor: '#C9D4DF',
        accentColor: '#FFC24A',
        layout: 'minimal',
        designTokens: {
          colors: { background: '#080B10', primary: '#FFC24A', secondary: '#F8FAFC', text: '#F8FAFC', card: '#131820' },
          typography: { fontFamily: '"Trebuchet MS", "Segoe UI", sans-serif', customFontUrl: '', originalFont: 'Trebuchet MS', textTransform: 'uppercase', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: '1px solid rgba(255,194,74,0.22)' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'service-authority-3',
        headline: 'Quando a luz cai, sua marca precisa aparecer.',
        body: 'Versão mais memorável para destacar disponibilidade e resposta rápida.',
        caption: 'Quando a luz cai, sua marca precisa aparecer.\n\nVersão mais memorável para destacar disponibilidade e resposta rápida.',
        callToAction: 'Salvar contato',
        imagePrompt: 'dramatic city lights, power outage mood, professional emergency service ad',
        imageUrl: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#05060A',
        textColor: '#FFFFFF',
        headlineColor: '#FFFFFF',
        bodyColor: '#D7DDE6',
        accentColor: '#5CE1E6',
        layout: 'centered',
        designTokens: {
          colors: { background: '#05060A', primary: '#5CE1E6', secondary: '#FFFFFF', text: '#FFFFFF', card: '#10131B' },
          typography: { fontFamily: '"Segoe UI", "Helvetica Neue", sans-serif', customFontUrl: '', originalFont: 'Segoe UI', textTransform: 'none', textAlign: 'center' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: 'none' },
          decorations: 'minimal',
        },
      },
    ],
  },
  {
    id: 'beauty-salon-campaign',
    chip: 'Beleza',
    title: 'Salão de beleza enchendo a agenda',
    prompt: 'tenho salão de beleza e quero divulgar agenda aberta sem parecer post genérico',
    outcome: 'Três direções com cara de marca: agenda, prova social e campanha pronta para publicar.',
    variations: [
      {
        ...baseVariation,
        id: 'beauty-salon-campaign-1',
        headline: 'Agenda aberta para sair do salão se sentindo pronta.',
        body: 'Uma chamada elegante para transformar desejo de cuidado em horário marcado.',
        caption: 'Agenda aberta para sair do salão se sentindo pronta.\n\nUma chamada elegante para transformar desejo de cuidado em horário marcado.',
        callToAction: 'Reservar horário',
        imagePrompt: 'premium beauty salon chair, polished mirror, warm editorial lighting, elegant brand campaign',
        imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#120B10',
        textColor: '#FFF6FB',
        headlineColor: '#FFF6FB',
        bodyColor: '#EAD7E2',
        accentColor: '#FF6FAE',
        layout: 'split',
        designTokens: {
          colors: { background: '#120B10', primary: '#FF6FAE', secondary: '#FFF6FB', text: '#FFF6FB', card: '#24131E' },
          typography: { fontFamily: '"Arial Black", "Arial", sans-serif', customFontUrl: '', originalFont: 'Arial Black', textTransform: 'uppercase', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: '0 18px 40px rgba(0,0,0,0.42)', border: 'none' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'beauty-salon-campaign-2',
        headline: 'Antes de escolher um salão, ela precisa confiar.',
        body: 'Prova social com visual limpo para mostrar cuidado, técnica e consistência.',
        caption: 'Antes de escolher um salão, ela precisa confiar.\n\nProva social com visual limpo para mostrar cuidado, técnica e consistência.',
        callToAction: 'Ver transformações',
        imagePrompt: 'minimal beauty salon details, hair tools, soft beige counter, premium editorial composition',
        imageUrl: 'https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#F6EEE7',
        textColor: '#1B1514',
        headlineColor: '#1B1514',
        bodyColor: '#514240',
        accentColor: '#C25A7C',
        layout: 'minimal',
        designTokens: {
          colors: { background: '#F6EEE7', primary: '#C25A7C', secondary: '#1B1514', text: '#1B1514', card: '#E7D8CF' },
          typography: { fontFamily: 'Georgia, "Times New Roman", serif', customFontUrl: '', originalFont: 'Georgia', textTransform: 'none', textAlign: 'left' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: 'none' },
          decorations: 'minimal',
        },
      },
      {
        ...baseVariation,
        id: 'beauty-salon-campaign-3',
        headline: 'Sua próxima transformação já pode ter data.',
        body: 'Campanha mais marcante para agenda aberta, pacote de beleza ou semana especial.',
        caption: 'Sua próxima transformação já pode ter data.\n\nCampanha mais marcante para agenda aberta, pacote de beleza ou semana especial.',
        callToAction: 'Quero meu horário',
        imagePrompt: 'bold beauty salon campaign, glossy hair, black and hot pink editorial poster, premium social media ad',
        imageUrl: 'https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=900&q=80',
        backgroundColor: '#080507',
        textColor: '#FFFFFF',
        headlineColor: '#FFFFFF',
        bodyColor: '#F0DDE7',
        accentColor: '#FF3F92',
        layout: 'centered',
        designTokens: {
          colors: { background: '#080507', primary: '#FF3F92', secondary: '#FFFFFF', text: '#FFFFFF', card: '#180D14' },
          typography: { fontFamily: '"Trebuchet MS", "Segoe UI", sans-serif', customFontUrl: '', originalFont: 'Trebuchet MS', textTransform: 'uppercase', textAlign: 'center' },
          structure: { borderRadius: '0px', boxShadow: 'none', border: '1px solid rgba(255,79,147,0.22)' },
          decorations: 'minimal',
        },
      },
    ],
  },
];

export function createLanding2Snapshot(variation: PostVariation) {
  return createPostVisualSnapshot(variation, '1:1');
}
